name: cote_pat
description: A new Flutter project.



publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons:
  hexcolor: 
  font_awesome_flutter:
  otp_text_field: 
  cloud_firestore:
  intl: 
  group_button: ^4.8.0
  maps_launcher:
  share_plus_web:
  table_calendar:
  flutter_phone_direct_caller: 
  pdf: 
  path_provider: 
  open_file: 
  get: 
  firebase_auth:
  firebase_auth_web: 
  google_sign_in: 
  google_sign_in_web:
  basic_utils: 
  image_picker:
  flutter_rating_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter









  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true

  
  assets:
  - img/
  - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf