name: cote_pat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1
  cloud_firestore: ^3.1.13
  intl: ^0.17.0
  group_button: ^4.8.0
  maps_launcher: ^2.0.1
  share_plus_web: ^3.0.0
  table_calendar: ^3.0.5
  flutter_phone_direct_caller: ^2.1.1
  pdf: ^3.8.0
  path_provider: ^2.0.10
  open_file: ^3.2.1
  get: ^4.6.1
  firebase_auth: ^3.3.18
  firebase_auth_web: ^3.3.15
  google_sign_in: ^5.3.1
  google_sign_in_web: ^0.10.1+2
  basic_utils: ^4.2.2
  image_picker: ^0.8.5
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  firebase_analytics: ^9.1.8
  file_picker: ^4.6.1
  firebase_storage: ^10.2.17
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo copie.png"
  flutter_lints: ^1.0.0





flutter:




  uses-material-design: true


  assets:
  - assets/images/
  - assets/
  - img/



